int w = 130;
int h = 200;
boolean selected = false;
ArrayList<card> cards = new ArrayList();
ArrayList<card> stack = new ArrayList();
ArrayList<card> stack2 = new ArrayList();
ArrayList<card> goal1 = new ArrayList();
ArrayList<card> goal2 = new ArrayList();
ArrayList<card> goal3 = new ArrayList();
ArrayList<card> goal4 = new ArrayList();
ArrayList<card> mid1 = new ArrayList();
ArrayList<card> mid2 = new ArrayList();
ArrayList<card> mid3 = new ArrayList();
ArrayList<card> mid4 = new ArrayList();
ArrayList<card> mid5 = new ArrayList();
ArrayList<card> mid6 = new ArrayList();
ArrayList<card> mid7 = new ArrayList();

ArrayList<stack> stacks = new ArrayList();
PImage heart,diamond,clover,spade,sheart,sdiamond,sclover,sspade;
